title: <p align="center"> Yogesh Deo </p>

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/yogeshdeokar/">LinkedIn</a> |
  <a href="https://github.com/yogeshdeo91">GitHub</a>
  </p>
  
  <p align="justify">
 I turn data into stories that drive smart decisions! With a love for digging into complex datasets, 
 I specialise in creating clear, impactful visualizations and models that help businesses grow.Skilled in tools like SQL, Power BI, Tableau, and R, 
 I blend analytical thinking with creativity to uncover insights, predict trends, and solve problems. 
 When I’m not crunching numbers, you can find me watching movies, exploring new cuisines, or planning my next travel adventure. 
 Let’s get those numbers working for you!
  <br><br>
  <br><br>
  </p>

# Social Links
social:
  github: https://github.com/yogeshdeo91
  linkedin: https://www.linkedin.com/in/yogeshdeokar


# SEO & Meta Tags
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# Optional: If you want to include Markdown documentation pages
markdown: kramdown

# Exclude files from the site build
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - node_modules/

# Customize Minima Theme
minima:
  skin: "classic" # Change to "dark" or "solarized" if you'd like a different look

# Navigation Links (Optional)
header_pages:
  - projects.md
  - about.md
  - blog.md

# Pagination (if you have a blog)
paginate: 5
paginate_path: "/blog/page:num"

# Enable Table of Contents (Optional)
toc: true
